<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Click to Say Hello</name>
   <tag></tag>
   <elementGuidId>79c082f3-9ac9-4b68-93df-ad650a4760b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;say_hello&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='say_hello']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Click to Say Hello&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4b5d2e1-afff-44eb-80ac-eadf1a173885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>777ab87e-4664-4644-a793-6ca3977e36b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>say_hello</value>
      <webElementGuid>d72a4f3a-0fcc-45a8-ab55-89c68d93b76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click to Say Hello</value>
      <webElementGuid>62766c40-fcc0-4e8e-9f24-99b2d9627b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/button[1]</value>
      <webElementGuid>e3c1e187-919d-48dc-a9ad-d5b78daac133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='say_hello']</value>
      <webElementGuid>caf6f937-c0e6-4a73-99f1-00ca7c476872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flask Form Example'])[1]/following::button[1]</value>
      <webElementGuid>2b298d37-26d4-4f55-8e06-f6bde28dfb56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/html[1]/body[1]/form[1]/button[1]'])[1]/preceding::button[1]</value>
      <webElementGuid>54965396-2e0a-44b5-b577-d223e56e7ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Click to Say Hello']/parent::*</value>
      <webElementGuid>efc850b6-2243-4aa7-a041-264aeffc9e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6af5618a-4c5b-491f-80e5-edca484744ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'say_hello' and (text() = 'Click to Say Hello' or . = 'Click to Say Hello')]</value>
      <webElementGuid>54d5d26e-1aca-489e-8a32-36803aba199f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
